### ISSUE TITLE
Support Dropbox APIv2

### ISSUE THREAD

**Issue by awead** [samvera/browse-everything#159]
Dropbox has deprecated their APIv1 and we need to ensure everything works with the new one.

See https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by awead** [comment]
We're currently dropbox-sdk, and from the looks of it, there is no plan for it to be updated to support v2. See https://github.com/dropbox/dropbox-sdk-ruby/issues/41

**Comment by no-reply** [comment]
The v1 APIs are now retired; see: https://www.dropbox.com/developers/reference/migration-guide h/t @mjgiarlo
