### ISSUE TITLE
Is Skydrive dead?  Can we remove support?

### ISSUE THREAD

**Issue by jcoyne** [samvera/browse-everything#170]
/cc @cam156 @mbklein @awead @scherztc

**Comment by awead** [comment]
@jcoyne it's now MS OneDrive https://support.microsoft.com/en-us/help/17787/skydrive-to-onedrive

so, yeah, we can remove it.

**Comment by jcoyne** [comment]
@awead if you use that, do you want to replace it with the onedrive gem?

**Comment by awead** [comment]
@jcoyne we don't use it, that I know of, so implementing OneDrive could be a separate issue.

**Comment by jrgriffiniii** [comment]
Is this still an active issue?  I ask only given that there don't appear to be many (well) maintained OneDrive Gems:
- https://github.com/jrom/onedrive-ruby
- https://github.com/aj-michael/onedrive

**Comment by geekscruff** [comment]
I think this should be closed. If someone needs OneDrive (and we might at some point), then they should create a new issue.
