### ISSUE TITLE
Google Drive: link_for method returns empty url

### ISSUE THREAD

**Issue by scherztc** [samvera/browse-everything#177]
Since moving up to Google Drive Api version 3 the link_for method is returns an empty url.

This empty url does not let browse_everything retrieve the file.

**Comment by scherztc** [comment]
@mjgiarlo Attaching a file from google_drive is broken.  The attached file display only shows the name.  It displays 0 KB and web_content_link is Nil.  Creating empty records in our hyrax application.

Our engine_cart test application does not increment the attached file display when using google_drive.

Currently there are no unit test for google_drive : https://github.com/samvera/browse-everything/tree/master/spec/unit.  I can certainly add one when I figure out what is going on.

**Comment by awead** [comment]
@scherztc You can write a unit test for Google Drive by cribbing from one of the existing tests for the other drives. Take a look at what I did for https://github.com/samvera/browse-everything/blob/master/spec/unit/box_spec.rb, in particular, https://github.com/samvera/browse-everything/blob/master/spec/unit/box_spec.rb#L16-L28

I had to have a live-running connection during the test to see what was actually coming back from Box, then write the tests. Once I the tests passed with the live data from Box, I recorded the responses with VCR. The annoying thing with that was that the tokens expired after an hour.

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/blob/77140b38907158aaa4e30aae442ea5f04d0b1be2/app/jobs/import_url_job.rb#L53

I feel like URI isn't enough for Google Drive to work using the retriever. I think we need more header information, particularly mime-type. HTTPParty is returning a Moved Temporarily error.

**Comment by mjgiarlo** [comment]
How is this looking, @jrgriffiniii?

**Comment by jrgriffiniii** [comment]
@mjgiarlo a rudimentary unit test has been provided using a [WIP] PR, and I'm going to continue looking towards reproducing the empty URL issue.

**Comment by mjgiarlo** [comment]
@jrgriffiniii I'd probably tackle #159 in advance of the Hyrax integration work just in case you find that the new Dropbox API also requires changes to `ImportUrlJob` -- then you can tackle that in one new Hyrax PR instead of two. Does that make sense?

**Comment by jrgriffiniii** [comment]
@scherztc returning to the concerns you expressed over `BrowseEverything::Retriever` within `ImportUrlJob` for Hyrax, do you feel as if this is progressing in the right direction:
https://github.com/jrgriffiniii/hyrax/commit/d59ed7341198103ec5e2b3cf2c920c70d97e39f6

**Comment by scherztc** [comment]
I think this may be the right direction.  I will test it today.
