### ISSUE TITLE
Google Chrome crashes on Travis CI

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/browse-everything#193]
The following error was encountered for acceptance tests within the Travis CI build environment:
```
Selenium::WebDriver::Error::UnknownError:
       unknown error: Chrome failed to start: crashed
```

**Comment by cjcolvar** [comment]
See @mjgiarlo's commit to hyrax about this issue: https://github.com/samvera/hyrax/pull/2462/commits/eacbdcb3070411605d71189224c40f20873a35d9

**Comment by jrgriffiniii** [comment]
Various improvements have been addressed and this is again prepared for review.
