### ISSUE TITLE
Refactor UI

### ISSUE THREAD

**Issue by mbklein** [samvera/browse-everything#210]
- [ ] Stop rendering HTML server-side
- [ ] Remove the dependency on jquery-treeTable
- [ ] Make the client-side experience smoother
- [ ] Maintain API compatibility with previous versions

**Comment by hackmastera** [comment]
Along the lines of "make the client-side experience smoother" I have observed users having trouble targeting the small checkbox with a mouse. Perhaps making a click target out of the whole row would be helpful; I think this would be in line with general expected checkbox behavior.

**Comment by jrochkind** [comment]
@hackmastera on my install of 0.15.1, you _can_ click on the _name_ of the file to select the checkbox. But yeah, whole row is a good idea. I bet one could hack that in locally with some JS?

**Comment by jrgriffiniii** [comment]
> Stop rendering HTML server-side

I would argue in favor of supporting responses which are compliant with the JSON-API specification for serving the data, with client-side JavaScript primarily handling the rendering the data.

**Comment by jrgriffiniii** [comment]
> Make the client-side experience smoother

This is going to probably require another issue, and I would advocate here for exploring at least one JavaScript framework to supercede the current usage of jQuery.

**Comment by adamjarling** [comment]
@jrgriffiniii Many moons ago when we had a brief lull here, I started looking into this with ReactJS, and because the application was a Rails engine, ran into some problems getting `webpacker` integrated.  Not sure if this is still relevant or not, or whether the latest `webpacker` supports Rails engines?  @cjcolvar has done some related work on integrating Rails/Webpacker and might have some insight?

**Comment by jrochkind** [comment]
The official Rails answer for Engines and Webpacker seems to be -- engines should release their JS as an npm package. Then the dependent app should just depend on the rails gem in it's gemfile, and the npm package in it's yarn file, and make sure to keep them in sync (there's no automated way to ensure that). 

Some people have found somewhat hacky ways to try to do things differently. 

I'm not totally happy with any of the approaches, official rails answer or other. 

The most useful discussion seems to be at: https://github.com/rails/webpacker/issues/348

**Comment by jrochkind** [comment]
One of the tricks with a dependency on React (or vue for that matter) is that those are fairly heavy-weight dependencies to force an app to use. An app may want to use b-e without previously using react or vue -- or worse, maybe the app already uses react or vue, whichever one _isn't_ the one BE is using.  There could be conflicts, or in the best case, just a lot of bytes of JS dependencies and a lot of JS running in the browser. 

I wonder if there's a lighter wait but still "more modern than JQuery" toolkit that could be useful. Some of the ones I've heard about include the Basecamp/Rails-affiliated [stimulus](https://github.com/stimulusjs/stimulus) (I'm not sure it does what you're looking for), and [mithril](https://mithril.js.org/) (looks more interesting to me). 

In general, I find the JS landscape these days pretty overwhelming, especially for figuring out how to supply with a Rails engine.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera-labs/samvera-connect/issues/231 might be of interest (in terms of using established patterns for replacing jQuery).

**Comment by jrgriffiniii** [comment]
`Stop rendering HTML server-side` and `Remove the dependency on jquery-treeTable` are already addressed by https://github.com/samvera/browse-everything/compare/next/rails-api/jrgriffiniii and https://github.com/samvera-labs/browse-everything-redux-react

`Make the client-side experience smoother` will be a user experience issue for https://github.com/samvera-labs/browse-everything-redux-react. I can create an issue for `Maintain API compatibility with previous versions`

**Comment by jrgriffiniii** [comment]
Closing in favor of focusing upon https://github.com/samvera/browse-everything/issues/318
