### ISSUE TITLE
S3 driver returns only URL in AJAX response, not filename or size

### ISSUE THREAD

**Issue by jrochkind** [samvera/browse-everything#213]
It may be that the size is not available from the API calls being used. 

But a filename could at least be extracted from the URL (as it is in the _listings_ already), which would be a convenient normalization to perform before returning data to a client, so the client which is expecting a filename does not have to do it itself, so clients could assume a filename would always be provided and not have to implement the logic themselves to extract it from the URL if they need one. The logic ought to be inside browse_everything.

**Comment by jrgriffiniii** [comment]
Closed by #216
