### ISSUE TITLE
Browse-everything should not require sprockets 3.x only

### ISSUE THREAD

**Issue by jrochkind** [samvera/browse-everything#310]
In the 1.0.2 release, b-e starts insisting on sprockets 3.x, when it never did before. https://github.com/samvera/browse-everything/compare/v1.0.1...v1.0.2#diff-5bf8d919175f7b1e1ffb5930b515cbe7R32

I had already updated my app (in a branch not yet merged) to sprockets 4. This means I can't upgrade to sprockets 1.0.2 -- at least without downgrading my app back to sprockets 3 again. But sprockets 4 is the supported sprockets version, and has advantages like supporting sourcemaps. 

B-e should not do this in a patch release, but also I think should not do it at all, there is no reason I know of that b-e should care about version of sprockets used. I suspect it's an issue, if anything, with automatic app-generation for automatic engine-cart-based testing. 

It's possible that sprockets 4 requires edits to the default manifest.js and/or any automatically-generated .js files to be generated in sub-directories instead of root `./app/assets`. But as a develoepr using b-e, I _could_ do these things manually, but the gemspec restriction means it is impossible to use sprockets 4 no matter what. 

As a "lesser evil" fix, you could only *test* with sprockets 3, without actually restricting dependers to only using sprockets 4. Not ideal, but at least it wouldn't keep users of b-e from using sprockets 4. 

Some info on the sprockets 4 upgrade, and why it broke Rails apps even though it wasn't intended to:

* https://github.com/rails/sprockets/blob/master/UPGRADING.md
* https://bibwild.wordpress.com/2019/10/15/sprockets-4-and-your-rails-app/

**Comment by jrgriffiniii** [comment]
This is blocked by a `sass-rails` dependency that I'm working to resolve (`engine_cart` requires that the `Gemfile` be modified using a `gsub` for the version of this Gem).

**Comment by jrgriffiniii** [comment]
I have a solution with https://github.com/samvera/browse-everything/compare/master...jrgriffiniii:issues-310-jrgriffiniii-sprockets-4, but it still will not necessarily support Rails 6.0.0 given what I'm finding with the following:

```bash
% rails _6.0.0_ new test-rails-app
...
✨  Done in 7.49s.
Webpacker successfully installed 🎉 🍰
```

...but when I visit the new Rails application, I find this in the `Gemfile`:
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5'
```

Hence, one needs to manually update the dependency for `sass-rails` before Rails 6.0.z releases can be used with this Gem.

**Comment by jrgriffiniii** [comment]
Rails 6.0.1 should address this with https://github.com/rails/rails/issues/36954#issuecomment-522171807

**Comment by jrochkind** [comment]
OK, I think we may not be quite on the same page. 

It is true that a Rails-generated Gemfile locks to sass-rails 5.x, which keeps sprockets 4 from being used without a manual Gemfile change. 

I don't believe this is browse-everything's responsibility to fix. 

I am ambivalent/unsure on whether browse-everything needs to be _tested_ under sprockets 4 -- ie, if it needs to `gsub` the Rails-generated gemfile in the engine_cart-generated app in order to do so. 

But right now if I as a developer _do_ manually change my Gemfile to allow sass-rails 6.0 (some people already have to avoid the deprecation warning on ruby-sass) -- browse-everything will itself prevent from using sprockets 4 with it's own gemspec saying `sprockets, '~> 3.7'` and locking to sprockets 3.x Which was introduced only browse-everything 1.0.2, before that I don't believe browse-everything gemspec required any particular version of sprockets. 

The only thing I"m suggesting is that browse-everything ought not to lock down sprockets to 3.x, and ought not to have introduced this lock down in 1.0.2, so it should be removed in a 1.0.3. That's it. It's not browse-everything's responsiblity to do anythign with the Rails-generated Gemfile's insistence on `sass-rails` 5.x -- browse-everything just shouldn't _get in the way_ of a developer manually doing so themselves. 

Does that make sense?

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/browse-everything/pull/358 resolved this.
