### ISSUE TITLE
browse_everything prevents using thor 1.0

### ISSUE THREAD

**Issue by jrochkind** [samvera/browse-everything#338]
the `thor` gem had a 1.0 release on December 13 2019. 

browse_everything's gemspec prevents an app using browse_everything from using thor 1.0. 

https://github.com/samvera/browse-everything/blob/78706504b0b16588ae6e41dfa2ac3cf38cb3d018/browse-everything.gemspec#L33

Rails itself allows any thor `(>= 0.20.3, < 2.0)`, so it allows all 1.x. 

Can browse_everything do the same? Is the `thor` dependency needed at all?

**Comment by jeremyf** [comment]
I think my preference would be to preserve the explicit dependency, but ease the restriction. From a historical context perspective, I believe the community has opted to tighten its constraints on pre v1.0.0 releases. I think easing the restriction makes sense. @jrgriffiniii the annotation points to 4bbb72ed253328f649f0a3b4c96258a1035e156d for Thor dependency with the message:

> Ensuring that the region config. for the Amazon S3 provider is required; Removing parent directories with relative path entries (..) from the S3 and Box providers; Using thor 0.19 as a release dependency

Any thoughts or insights?

**Comment by jrochkind** [comment]
> I think my preference would be to preserve the explicit dependency, but ease the restriction.

@jeremyf this makes sense if `browse-everything` *uses thor*.  Then it should be declared as a dependency. Like if thor is needed for browse-everything to work -- declaring it as a dependency says that, and allows you to set a restriction range, because if thor's api changes in backwards-incompat ways, browse-everything's use of it might break. 

Does browse-everything use thor?

**Comment by jeremyf** [comment]
Good catch, BE does not use Thor directly, but instead relies on the Rails Generator. I'll submit a PR to get rid of the explicit dependency. Let the downstream deal with the lock version.
