### ISSUE TITLE
Support Rails 6.1 releases

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/browse-everything#372]
Derived from https://github.com/samvera/maintenance/issues/76

**Comment by jrgriffiniii** [comment]
https://github.com/jrgriffiniii/rails6.1-engine-tutorial is starting to again familiarize me with the preferred approach for addressing the Rails Engine support in Rails 6.1 releases.

**Comment by jrochkind** [comment]
I am using this with Rails 6.1, so it does work!   Also it seems to be tested on rails 6.1 in CircleCI already? 

Curious as to your thoughts on what would change to approach Rails 6.1 better. 

(also, the circleCI icon on readme is green, but when I click on it... I seem to see failing jobs? Which is disturbing).
