### ISSUE TITLE
Support Ruby 3.0.3 releases

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/browse-everything#373]
Derived from https://github.com/samvera/maintenance/issues/77

**Comment by jrgriffiniii** [comment]
https://github.com/samvera-labs/samvera-circleci-orb/issues/55 is blocking this.

**Comment by jrgriffiniii** [comment]
There are now additional failures for the CircleCI build for 3.0.3 Ruby releases:

```
Using bootstrap 4.6.1
Errno::ENOENT: No such file or directory @ rb_sysopen -
/home/circleci/project/vendor/bundle/ruby/3.0.0/specifications/puma-3.12.6.gemspec
An error occurred while installing sync (0.5.0), and Bundler cannot
continue.
Make sure that `gem install sync -v '0.5.0' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  coveralls was resolved to 0.7.1, which depends on
    term-ansicolor was resolved to 1.7.1, which depends on
      tins was resolved to 1.31.0, which depends on
        sync

Exited with code exit status 5
CircleCI received exit code 5
```

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/maintenance/issues/81#issuecomment-1077883434 was discovered when addressing this. I shall adjust accordingly.

**Comment by jrochkind** [comment]
Rails 5.2 is not supported on ruby 3, so that test failure is expected.  Just don't test 5.2 on Ruby 3+. 

https://github.com/rails/rails/issues/40938#issuecomment-751357907
