### ISSUE TITLE
Create Version 1.0

### ISSUE THREAD

**Issue by cam156** [samvera/browse-everything#76]
Declare that this is the supported interface by defining 1.0.0

**Comment by jrgriffiniii** [comment]
Depends on #233

**Comment by jrgriffiniii** [comment]
Blocked by #233

**Comment by jrgriffiniii** [comment]
Blocked by #235.

**Comment by jrgriffiniii** [comment]
Blocked by #215.

**Comment by jrgriffiniii** [comment]
This was resolved by @mbklein with https://github.com/samvera/browse-everything/commit/8ad9ecc4bd18b7e9c7a051db668c8c7467b51b9e.
